import type { RoutineTemplate } from '../../../domain/models/RoutineTemplate';

export const TEMPLATES: RoutineTemplate[] = [
  {
    id: 'fb-gym-3d',
    name: 'Full Body — Gimnasio 3 días',
    description:
      'Rutina de cuerpo completo en gimnasio. Tres sesiones por semana centradas en los movimientos básicos.',
    goal: 'GAIN_MUSCLE',
    equipment: 'FULL_GYM',
    level: 'BEGINNER',
    daysPerWeek: 3,
    estimatedDurationMin: 60,
    routines: [
      {
        name: 'Día A — Empuje',
        exercises: [
          {
            name: 'Barbell back squat',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '8-10',
            restSeconds: 120,
          },
          {
            name: 'Barbell bench press',
            muscleGroup: 'Pecho',
            sets: 3,
            reps: '8-10',
            restSeconds: 90,
          },
          {
            name: 'Standing overhead press',
            muscleGroup: 'Hombro',
            sets: 3,
            reps: '8-10',
            restSeconds: 90,
          },
          {
            name: 'Barbell bent-over row',
            muscleGroup: 'Espalda',
            sets: 3,
            reps: '8-10',
            restSeconds: 90,
          },
          {
            name: 'Front plank',
            muscleGroup: 'Core',
            sets: 3,
            reps: '30-45s',
            restSeconds: 45,
          },
        ],
      },
      {
        name: 'Día B — Tracción',
        exercises: [
          {
            name: 'Conventional deadlift',
            muscleGroup: 'Espalda',
            sets: 3,
            reps: '6-8',
            restSeconds: 150,
          },
          {
            name: 'Incline dumbbell bench press',
            muscleGroup: 'Pecho',
            sets: 3,
            reps: '10-12',
            restSeconds: 90,
          },
          {
            name: 'Lat pulldown',
            muscleGroup: 'Espalda',
            sets: 3,
            reps: '10-12',
            restSeconds: 75,
          },
          {
            name: 'Barbell curl',
            muscleGroup: 'Bíceps',
            sets: 3,
            reps: '10-12',
            restSeconds: 60,
          },
          {
            name: 'Triceps cable pushdown',
            muscleGroup: 'Tríceps',
            sets: 3,
            reps: '10-12',
            restSeconds: 60,
          },
        ],
      },
      {
        name: 'Día C — Pierna y core',
        exercises: [
          {
            name: 'Barbell hip thrust',
            muscleGroup: 'Glúteo',
            sets: 4,
            reps: '10-12',
            restSeconds: 90,
          },
          {
            name: 'Leg press',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '10-12',
            restSeconds: 90,
          },
          {
            name: 'Lying leg curl',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '10-12',
            restSeconds: 75,
          },
          {
            name: 'Standing calf raise',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '12-15',
            restSeconds: 60,
          },
          {
            name: 'Cable crunch',
            muscleGroup: 'Core',
            sets: 3,
            reps: '12-15',
            restSeconds: 60,
          },
        ],
      },
    ],
  },
  {
    id: 'fb-home-3d',
    name: 'Full Body — Casa con pesos 3 días',
    description:
      'Cuerpo completo con mancuernas en casa. Ideal para empezar sin necesidad de gimnasio.',
    goal: 'GAIN_MUSCLE',
    equipment: 'HOME_WEIGHTS',
    level: 'BEGINNER',
    daysPerWeek: 3,
    estimatedDurationMin: 50,
    routines: [
      {
        name: 'Día A',
        exercises: [
          {
            name: 'Goblet squat',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '10-12',
            restSeconds: 90,
          },
          {
            name: 'Dumbbell floor press',
            muscleGroup: 'Pecho',
            sets: 3,
            reps: '10-12',
            restSeconds: 75,
          },
          {
            name: 'One-arm dumbbell row',
            muscleGroup: 'Espalda',
            sets: 3,
            reps: '10-12',
            restSeconds: 75,
          },
          {
            name: 'Seated dumbbell shoulder press',
            muscleGroup: 'Hombro',
            sets: 3,
            reps: '10-12',
            restSeconds: 75,
          },
          {
            name: 'Front plank',
            muscleGroup: 'Core',
            sets: 3,
            reps: '30s',
            restSeconds: 45,
          },
        ],
      },
      {
        name: 'Día B',
        exercises: [
          {
            name: 'Dumbbell Romanian deadlift',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '10-12',
            restSeconds: 90,
          },
          {
            name: 'Dumbbell floor fly',
            muscleGroup: 'Pecho',
            sets: 3,
            reps: '10-12',
            restSeconds: 60,
          },
          {
            name: 'Dumbbell rear delt fly',
            muscleGroup: 'Hombro',
            sets: 3,
            reps: '12-15',
            restSeconds: 60,
          },
          {
            name: 'Dumbbell bicep curl',
            muscleGroup: 'Bíceps',
            sets: 3,
            reps: '10-12',
            restSeconds: 60,
          },
          {
            name: 'Triceps kickback',
            muscleGroup: 'Tríceps',
            sets: 3,
            reps: '10-12',
            restSeconds: 60,
          },
        ],
      },
      {
        name: 'Día C',
        exercises: [
          {
            name: 'Bulgarian split squat (dumbbells)',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '10-12',
            restSeconds: 90,
          },
          {
            name: 'Dumbbell hip thrust',
            muscleGroup: 'Glúteo',
            sets: 3,
            reps: '12-15',
            restSeconds: 75,
          },
          {
            name: 'Renegade row',
            muscleGroup: 'Espalda',
            sets: 3,
            reps: '8-10',
            restSeconds: 75,
          },
          {
            name: 'Dumbbell shrug',
            muscleGroup: 'Espalda',
            sets: 3,
            reps: '12-15',
            restSeconds: 60,
          },
          {
            name: 'Weighted crunch',
            muscleGroup: 'Core',
            sets: 3,
            reps: '12-15',
            restSeconds: 60,
          },
        ],
      },
    ],
  },
  {
    id: 'fb-bw-3d',
    name: 'Full Body — Bodyweight 3 días',
    description:
      'Cuerpo completo solo con peso corporal. Sin material, ideal para empezar a moverse.',
    goal: 'HEALTH',
    equipment: 'BODYWEIGHT',
    level: 'BEGINNER',
    daysPerWeek: 3,
    estimatedDurationMin: 40,
    routines: [
      {
        name: 'Día A',
        exercises: [
          {
            name: 'Bodyweight squat',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '15-20',
            restSeconds: 60,
          },
          {
            name: 'Push-up',
            muscleGroup: 'Pecho',
            sets: 3,
            reps: '8-12',
            restSeconds: 60,
          },
          {
            name: 'Inverted row (table)',
            muscleGroup: 'Espalda',
            sets: 3,
            reps: '8-10',
            restSeconds: 75,
          },
          {
            name: 'Front plank',
            muscleGroup: 'Core',
            sets: 3,
            reps: '30-45s',
            restSeconds: 45,
          },
          {
            name: 'Glute bridge',
            muscleGroup: 'Glúteo',
            sets: 3,
            reps: '15-20',
            restSeconds: 45,
          },
        ],
      },
      {
        name: 'Día B',
        exercises: [
          {
            name: 'Alternating lunge',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '10/leg',
            restSeconds: 60,
          },
          {
            name: 'Incline push-up',
            muscleGroup: 'Pecho',
            sets: 3,
            reps: '10-12',
            restSeconds: 60,
          },
          {
            name: 'Superman',
            muscleGroup: 'Espalda',
            sets: 3,
            reps: '12-15',
            restSeconds: 45,
          },
          {
            name: 'Side plank',
            muscleGroup: 'Core',
            sets: 3,
            reps: '20-30s/side',
            restSeconds: 45,
          },
          {
            name: 'Wall handstand hold',
            muscleGroup: 'Hombro',
            sets: 3,
            reps: '8-10',
            restSeconds: 60,
          },
        ],
      },
      {
        name: 'Día C',
        exercises: [
          {
            name: 'Assisted pistol squat',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '6-8/leg',
            restSeconds: 75,
          },
          {
            name: 'Bench dip',
            muscleGroup: 'Tríceps',
            sets: 3,
            reps: '8-12',
            restSeconds: 60,
          },
          {
            name: 'Bird dog',
            muscleGroup: 'Core',
            sets: 3,
            reps: '10/side',
            restSeconds: 45,
          },
          {
            name: 'Mountain climber',
            muscleGroup: 'Core',
            sets: 3,
            reps: '30s',
            restSeconds: 45,
          },
          {
            name: 'Burpee',
            muscleGroup: 'Cuerpo completo',
            sets: 3,
            reps: '8-10',
            restSeconds: 60,
          },
        ],
      },
    ],
  },
  {
    id: 'ul-gym-4d',
    name: 'Upper/Lower — Gimnasio 4 días',
    description:
      'Tren superior y tren inferior alternos. Cuatro sesiones por semana, ideal para ganar músculo con experiencia previa.',
    goal: 'GAIN_MUSCLE',
    equipment: 'FULL_GYM',
    level: 'INTERMEDIATE',
    daysPerWeek: 4,
    estimatedDurationMin: 70,
    routines: [
      {
        name: 'Tren superior — Fuerza',
        exercises: [
          {
            name: 'Barbell bench press',
            muscleGroup: 'Pecho',
            sets: 4,
            reps: '5-6',
            restSeconds: 150,
          },
          {
            name: 'Barbell bent-over row',
            muscleGroup: 'Espalda',
            sets: 4,
            reps: '6-8',
            restSeconds: 120,
          },
          {
            name: 'Standing overhead press',
            muscleGroup: 'Hombro',
            sets: 3,
            reps: '6-8',
            restSeconds: 120,
          },
          {
            name: 'Weighted pull-up',
            muscleGroup: 'Espalda',
            sets: 3,
            reps: '6-8',
            restSeconds: 120,
          },
          {
            name: 'Barbell curl',
            muscleGroup: 'Bíceps',
            sets: 3,
            reps: '8-10',
            restSeconds: 75,
          },
          {
            name: 'Skull crusher',
            muscleGroup: 'Tríceps',
            sets: 3,
            reps: '8-10',
            restSeconds: 75,
          },
        ],
      },
      {
        name: 'Tren inferior — Fuerza',
        exercises: [
          {
            name: 'Barbell back squat',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '5-6',
            restSeconds: 180,
          },
          {
            name: 'Romanian deadlift',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '6-8',
            restSeconds: 150,
          },
          {
            name: 'Leg press',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '8-10',
            restSeconds: 90,
          },
          {
            name: 'Lying leg curl',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '10-12',
            restSeconds: 75,
          },
          {
            name: 'Standing calf raise',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '12-15',
            restSeconds: 60,
          },
          {
            name: 'Weighted plank',
            muscleGroup: 'Core',
            sets: 3,
            reps: '45s',
            restSeconds: 60,
          },
        ],
      },
      {
        name: 'Tren superior — Hipertrofia',
        exercises: [
          {
            name: 'Incline dumbbell bench press',
            muscleGroup: 'Pecho',
            sets: 4,
            reps: '10-12',
            restSeconds: 90,
          },
          {
            name: 'Neutral-grip lat pulldown',
            muscleGroup: 'Espalda',
            sets: 4,
            reps: '10-12',
            restSeconds: 90,
          },
          {
            name: 'Dumbbell lateral raise',
            muscleGroup: 'Hombro',
            sets: 4,
            reps: '12-15',
            restSeconds: 60,
          },
          {
            name: 'Machine row',
            muscleGroup: 'Espalda',
            sets: 3,
            reps: '10-12',
            restSeconds: 75,
          },
          {
            name: 'Hammer curl',
            muscleGroup: 'Bíceps',
            sets: 3,
            reps: '10-12',
            restSeconds: 60,
          },
          {
            name: 'Triceps cable pushdown',
            muscleGroup: 'Tríceps',
            sets: 3,
            reps: '10-12',
            restSeconds: 60,
          },
        ],
      },
      {
        name: 'Tren inferior — Hipertrofia',
        exercises: [
          {
            name: 'Barbell hip thrust',
            muscleGroup: 'Glúteo',
            sets: 4,
            reps: '10-12',
            restSeconds: 90,
          },
          {
            name: 'Bulgarian split squat',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '10-12',
            restSeconds: 90,
          },
          {
            name: 'Leg extension',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '12-15',
            restSeconds: 60,
          },
          {
            name: 'Seated leg curl',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '12-15',
            restSeconds: 60,
          },
          {
            name: 'Hip abductor machine',
            muscleGroup: 'Glúteo',
            sets: 3,
            reps: '12-15',
            restSeconds: 60,
          },
          {
            name: 'Cable crunch',
            muscleGroup: 'Core',
            sets: 3,
            reps: '12-15',
            restSeconds: 60,
          },
        ],
      },
    ],
  },
  {
    id: 'ul-home-4d',
    name: 'Upper/Lower — Casa con pesos 4 días',
    description:
      'Tren superior y tren inferior con mancuernas en casa. Cuatro sesiones para progresar sin gimnasio.',
    goal: 'GAIN_MUSCLE',
    equipment: 'HOME_WEIGHTS',
    level: 'INTERMEDIATE',
    daysPerWeek: 4,
    estimatedDurationMin: 60,
    routines: [
      {
        name: 'Tren superior A',
        exercises: [
          {
            name: 'Dumbbell floor press',
            muscleGroup: 'Pecho',
            sets: 4,
            reps: '8-10',
            restSeconds: 90,
          },
          {
            name: 'One-arm dumbbell row',
            muscleGroup: 'Espalda',
            sets: 4,
            reps: '8-10',
            restSeconds: 90,
          },
          {
            name: 'Dumbbell shoulder press',
            muscleGroup: 'Hombro',
            sets: 3,
            reps: '8-10',
            restSeconds: 75,
          },
          {
            name: 'Alternating dumbbell curl',
            muscleGroup: 'Bíceps',
            sets: 3,
            reps: '10-12',
            restSeconds: 60,
          },
          {
            name: 'Triceps kickback',
            muscleGroup: 'Tríceps',
            sets: 3,
            reps: '10-12',
            restSeconds: 60,
          },
        ],
      },
      {
        name: 'Tren inferior A',
        exercises: [
          {
            name: 'Goblet squat',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '8-10',
            restSeconds: 120,
          },
          {
            name: 'Dumbbell Romanian deadlift',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '8-10',
            restSeconds: 120,
          },
          {
            name: 'Bulgarian split squat (dumbbells)',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '10-12',
            restSeconds: 90,
          },
          {
            name: 'Dumbbell hip thrust',
            muscleGroup: 'Glúteo',
            sets: 3,
            reps: '12-15',
            restSeconds: 75,
          },
          {
            name: 'Dumbbell calf raise',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '15-20',
            restSeconds: 45,
          },
        ],
      },
      {
        name: 'Tren superior B',
        exercises: [
          {
            name: 'Incline dumbbell bench press',
            muscleGroup: 'Pecho',
            sets: 4,
            reps: '10-12',
            restSeconds: 75,
          },
          {
            name: 'Renegade row',
            muscleGroup: 'Espalda',
            sets: 4,
            reps: '8-10',
            restSeconds: 90,
          },
          {
            name: 'Dumbbell lateral raise',
            muscleGroup: 'Hombro',
            sets: 4,
            reps: '12-15',
            restSeconds: 60,
          },
          {
            name: 'Hammer curl',
            muscleGroup: 'Bíceps',
            sets: 3,
            reps: '10-12',
            restSeconds: 60,
          },
          {
            name: 'Dumbbell skull crusher',
            muscleGroup: 'Tríceps',
            sets: 3,
            reps: '10-12',
            restSeconds: 60,
          },
        ],
      },
      {
        name: 'Tren inferior B',
        exercises: [
          {
            name: 'Dumbbell walking lunge',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '10/leg',
            restSeconds: 90,
          },
          {
            name: 'Dumbbell sumo squat',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '10-12',
            restSeconds: 90,
          },
          {
            name: 'Hip thrust',
            muscleGroup: 'Glúteo',
            sets: 3,
            reps: '12-15',
            restSeconds: 75,
          },
          {
            name: 'Front plank',
            muscleGroup: 'Core',
            sets: 3,
            reps: '45s',
            restSeconds: 45,
          },
          {
            name: 'Side plank',
            muscleGroup: 'Core',
            sets: 3,
            reps: '30s/side',
            restSeconds: 45,
          },
        ],
      },
    ],
  },
  {
    id: 'ul-bw-4d',
    name: 'Upper/Lower — Bodyweight 4 días',
    description:
      'Tren superior y tren inferior solo con peso corporal. Para mantener nivel sin material.',
    goal: 'MAINTAIN',
    equipment: 'BODYWEIGHT',
    level: 'INTERMEDIATE',
    daysPerWeek: 4,
    estimatedDurationMin: 45,
    routines: [
      {
        name: 'Tren superior A',
        exercises: [
          {
            name: 'Push-up',
            muscleGroup: 'Pecho',
            sets: 4,
            reps: '12-15',
            restSeconds: 75,
          },
          {
            name: 'Pull-up',
            muscleGroup: 'Espalda',
            sets: 4,
            reps: '6-10',
            restSeconds: 90,
          },
          {
            name: 'Pike push-up',
            muscleGroup: 'Hombro',
            sets: 3,
            reps: '8-12',
            restSeconds: 75,
          },
          {
            name: 'Inverted row',
            muscleGroup: 'Espalda',
            sets: 3,
            reps: '10-12',
            restSeconds: 75,
          },
          {
            name: 'Bench dip',
            muscleGroup: 'Tríceps',
            sets: 3,
            reps: '10-12',
            restSeconds: 60,
          },
        ],
      },
      {
        name: 'Tren inferior A',
        exercises: [
          {
            name: 'Bodyweight squat',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '20-25',
            restSeconds: 75,
          },
          {
            name: 'Bulgarian split squat',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '12-15/leg',
            restSeconds: 75,
          },
          {
            name: 'Single-leg glute bridge',
            muscleGroup: 'Glúteo',
            sets: 3,
            reps: '12/leg',
            restSeconds: 60,
          },
          {
            name: 'Assisted pistol squat',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '6-8/leg',
            restSeconds: 75,
          },
          {
            name: 'Single-leg calf raise',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '15/leg',
            restSeconds: 45,
          },
        ],
      },
      {
        name: 'Tren superior B',
        exercises: [
          {
            name: 'Diamond push-up',
            muscleGroup: 'Tríceps',
            sets: 4,
            reps: '10-12',
            restSeconds: 75,
          },
          {
            name: 'Chin-up',
            muscleGroup: 'Bíceps',
            sets: 4,
            reps: '6-10',
            restSeconds: 90,
          },
          {
            name: 'Decline push-up',
            muscleGroup: 'Pecho',
            sets: 3,
            reps: '10-12',
            restSeconds: 75,
          },
          {
            name: 'Superman',
            muscleGroup: 'Espalda',
            sets: 3,
            reps: '15-20',
            restSeconds: 45,
          },
          {
            name: 'Wall handstand hold',
            muscleGroup: 'Hombro',
            sets: 3,
            reps: '8-12',
            restSeconds: 60,
          },
        ],
      },
      {
        name: 'Tren inferior B',
        exercises: [
          {
            name: 'Alternating lunge',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '12/leg',
            restSeconds: 75,
          },
          {
            name: 'Jump squat',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '10-12',
            restSeconds: 75,
          },
          {
            name: 'Sumo squat',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '15-20',
            restSeconds: 60,
          },
          {
            name: 'Front plank',
            muscleGroup: 'Core',
            sets: 3,
            reps: '45-60s',
            restSeconds: 45,
          },
          {
            name: 'Bird dog',
            muscleGroup: 'Core',
            sets: 3,
            reps: '12/side',
            restSeconds: 45,
          },
        ],
      },
    ],
  },
  {
    id: 'ppl-gym-6d-adv',
    name: 'Push/Pull/Legs — Gimnasio 6 días avanzado',
    description:
      'Empuje, tracción y pierna repetidos dos veces por semana. Volumen alto para usuarios avanzados.',
    goal: 'GAIN_MUSCLE',
    equipment: 'FULL_GYM',
    level: 'ADVANCED',
    daysPerWeek: 6,
    estimatedDurationMin: 75,
    routines: [
      {
        name: 'Push',
        exercises: [
          {
            name: 'Barbell bench press',
            muscleGroup: 'Pecho',
            sets: 4,
            reps: '6-8',
            restSeconds: 120,
          },
          {
            name: 'Standing overhead press',
            muscleGroup: 'Hombro',
            sets: 4,
            reps: '6-8',
            restSeconds: 120,
          },
          {
            name: 'Incline dumbbell bench press',
            muscleGroup: 'Pecho',
            sets: 4,
            reps: '8-10',
            restSeconds: 90,
          },
          {
            name: 'Dumbbell lateral raise',
            muscleGroup: 'Hombro',
            sets: 4,
            reps: '12-15',
            restSeconds: 60,
          },
          {
            name: 'Cable fly',
            muscleGroup: 'Pecho',
            sets: 3,
            reps: '12-15',
            restSeconds: 60,
          },
          {
            name: 'Triceps cable pushdown',
            muscleGroup: 'Tríceps',
            sets: 4,
            reps: '10-12',
            restSeconds: 60,
          },
        ],
      },
      {
        name: 'Pull',
        exercises: [
          {
            name: 'Conventional deadlift',
            muscleGroup: 'Espalda',
            sets: 4,
            reps: '5-6',
            restSeconds: 180,
          },
          {
            name: 'Weighted pull-up',
            muscleGroup: 'Espalda',
            sets: 4,
            reps: '6-8',
            restSeconds: 120,
          },
          {
            name: 'Barbell bent-over row',
            muscleGroup: 'Espalda',
            sets: 4,
            reps: '8-10',
            restSeconds: 90,
          },
          {
            name: 'Lat pulldown',
            muscleGroup: 'Espalda',
            sets: 3,
            reps: '10-12',
            restSeconds: 75,
          },
          {
            name: 'Cable rear delt fly',
            muscleGroup: 'Hombro',
            sets: 4,
            reps: '12-15',
            restSeconds: 60,
          },
          {
            name: 'EZ-bar curl',
            muscleGroup: 'Bíceps',
            sets: 4,
            reps: '8-10',
            restSeconds: 60,
          },
        ],
      },
      {
        name: 'Legs',
        exercises: [
          {
            name: 'Barbell back squat',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '5-6',
            restSeconds: 180,
          },
          {
            name: 'Barbell hip thrust',
            muscleGroup: 'Glúteo',
            sets: 4,
            reps: '8-10',
            restSeconds: 120,
          },
          {
            name: 'Romanian deadlift',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '8-10',
            restSeconds: 120,
          },
          {
            name: 'Leg press',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '10-12',
            restSeconds: 90,
          },
          {
            name: 'Lying leg curl',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '10-12',
            restSeconds: 60,
          },
          {
            name: 'Standing calf raise',
            muscleGroup: 'Pierna',
            sets: 5,
            reps: '12-15',
            restSeconds: 45,
          },
        ],
      },
    ],
  },
  {
    id: 'ppl-home-6d',
    name: 'Push/Pull/Legs — Casa con pesos 6 días',
    description:
      'PPL adaptado a mancuernas en casa. Seis sesiones por semana repitiendo el ciclo de tres.',
    goal: 'GAIN_MUSCLE',
    equipment: 'HOME_WEIGHTS',
    level: 'INTERMEDIATE',
    daysPerWeek: 6,
    estimatedDurationMin: 55,
    routines: [
      {
        name: 'Push',
        exercises: [
          {
            name: 'Dumbbell floor press',
            muscleGroup: 'Pecho',
            sets: 4,
            reps: '8-10',
            restSeconds: 90,
          },
          {
            name: 'Dumbbell shoulder press',
            muscleGroup: 'Hombro',
            sets: 4,
            reps: '8-10',
            restSeconds: 90,
          },
          {
            name: 'Dumbbell floor fly',
            muscleGroup: 'Pecho',
            sets: 3,
            reps: '10-12',
            restSeconds: 75,
          },
          {
            name: 'Dumbbell lateral raise',
            muscleGroup: 'Hombro',
            sets: 4,
            reps: '12-15',
            restSeconds: 60,
          },
          {
            name: 'Triceps kickback',
            muscleGroup: 'Tríceps',
            sets: 3,
            reps: '10-12',
            restSeconds: 60,
          },
          {
            name: 'Dumbbell skull crusher',
            muscleGroup: 'Tríceps',
            sets: 3,
            reps: '10-12',
            restSeconds: 60,
          },
        ],
      },
      {
        name: 'Pull',
        exercises: [
          {
            name: 'Dumbbell Romanian deadlift',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '8-10',
            restSeconds: 120,
          },
          {
            name: 'One-arm dumbbell row',
            muscleGroup: 'Espalda',
            sets: 4,
            reps: '8-10',
            restSeconds: 75,
          },
          {
            name: 'Renegade row',
            muscleGroup: 'Espalda',
            sets: 3,
            reps: '8-10',
            restSeconds: 75,
          },
          {
            name: 'Dumbbell rear delt fly',
            muscleGroup: 'Hombro',
            sets: 4,
            reps: '12-15',
            restSeconds: 60,
          },
          {
            name: 'Alternating dumbbell curl',
            muscleGroup: 'Bíceps',
            sets: 3,
            reps: '10-12',
            restSeconds: 60,
          },
          {
            name: 'Hammer curl',
            muscleGroup: 'Bíceps',
            sets: 3,
            reps: '10-12',
            restSeconds: 60,
          },
        ],
      },
      {
        name: 'Legs',
        exercises: [
          {
            name: 'Goblet squat',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '10-12',
            restSeconds: 90,
          },
          {
            name: 'Bulgarian split squat (dumbbells)',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '10-12',
            restSeconds: 90,
          },
          {
            name: 'Dumbbell hip thrust',
            muscleGroup: 'Glúteo',
            sets: 4,
            reps: '12-15',
            restSeconds: 75,
          },
          {
            name: 'Dumbbell walking lunge',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '10/leg',
            restSeconds: 75,
          },
          {
            name: 'Dumbbell calf raise',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '15-20',
            restSeconds: 45,
          },
          {
            name: 'Weighted plank',
            muscleGroup: 'Core',
            sets: 3,
            reps: '45s',
            restSeconds: 45,
          },
        ],
      },
    ],
  },
  {
    id: 'ppl-bw-6d',
    name: 'Push/Pull/Legs — Bodyweight avanzado 6 días',
    description:
      'PPL solo con peso corporal y barra para dominadas. Para usuarios con buen control y nivel.',
    goal: 'GAIN_MUSCLE',
    equipment: 'BODYWEIGHT',
    level: 'ADVANCED',
    daysPerWeek: 6,
    estimatedDurationMin: 50,
    routines: [
      {
        name: 'Push',
        exercises: [
          {
            name: 'Decline push-up',
            muscleGroup: 'Pecho',
            sets: 4,
            reps: '12-15',
            restSeconds: 75,
          },
          {
            name: 'Pike push-up',
            muscleGroup: 'Hombro',
            sets: 4,
            reps: '8-12',
            restSeconds: 75,
          },
          {
            name: 'Diamond push-up',
            muscleGroup: 'Tríceps',
            sets: 4,
            reps: '10-15',
            restSeconds: 60,
          },
          {
            name: 'Plyo push-up',
            muscleGroup: 'Pecho',
            sets: 3,
            reps: '6-8',
            restSeconds: 90,
          },
          {
            name: 'Bench dip',
            muscleGroup: 'Tríceps',
            sets: 4,
            reps: '12-15',
            restSeconds: 60,
          },
          {
            name: 'Hollow hold',
            muscleGroup: 'Core',
            sets: 3,
            reps: '30-45s',
            restSeconds: 45,
          },
        ],
      },
      {
        name: 'Pull',
        exercises: [
          {
            name: 'Pull-up',
            muscleGroup: 'Espalda',
            sets: 5,
            reps: '6-10',
            restSeconds: 120,
          },
          {
            name: 'Chin-up',
            muscleGroup: 'Bíceps',
            sets: 4,
            reps: '6-10',
            restSeconds: 90,
          },
          {
            name: 'Inverted row',
            muscleGroup: 'Espalda',
            sets: 4,
            reps: '10-12',
            restSeconds: 75,
          },
          {
            name: 'Superman',
            muscleGroup: 'Espalda',
            sets: 3,
            reps: '15-20',
            restSeconds: 45,
          },
          {
            name: 'Front plank',
            muscleGroup: 'Core',
            sets: 3,
            reps: '60s',
            restSeconds: 45,
          },
          {
            name: 'Side plank',
            muscleGroup: 'Core',
            sets: 3,
            reps: '30s/side',
            restSeconds: 45,
          },
        ],
      },
      {
        name: 'Legs',
        exercises: [
          {
            name: 'Pistol squat',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '6-8/leg',
            restSeconds: 90,
          },
          {
            name: 'Jump squat',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '12-15',
            restSeconds: 75,
          },
          {
            name: 'Bulgarian split squat',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '12-15/leg',
            restSeconds: 75,
          },
          {
            name: 'Single-leg glute bridge',
            muscleGroup: 'Glúteo',
            sets: 3,
            reps: '12-15/leg',
            restSeconds: 60,
          },
          {
            name: 'Single-leg calf raise',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '15-20/leg',
            restSeconds: 45,
          },
          {
            name: 'Mountain climber',
            muscleGroup: 'Core',
            sets: 3,
            reps: '45s',
            restSeconds: 45,
          },
        ],
      },
    ],
  },
  {
    id: 'fat-hiit-gym-4d',
    name: 'Quema grasa HIIT — Gimnasio 4 días',
    description:
      'Mezcla de fuerza y cardio HIIT. Cuatro sesiones intensas para perder grasa manteniendo masa muscular.',
    goal: 'LOSE_FAT',
    equipment: 'FULL_GYM',
    level: 'INTERMEDIATE',
    daysPerWeek: 4,
    estimatedDurationMin: 55,
    routines: [
      {
        name: 'Día A — Fuerza superior + cardio',
        exercises: [
          {
            name: 'Dumbbell bench press',
            muscleGroup: 'Pecho',
            sets: 4,
            reps: '12-15',
            restSeconds: 60,
          },
          {
            name: 'Machine row',
            muscleGroup: 'Espalda',
            sets: 4,
            reps: '12-15',
            restSeconds: 60,
          },
          {
            name: 'Machine shoulder press',
            muscleGroup: 'Hombro',
            sets: 3,
            reps: '12-15',
            restSeconds: 60,
          },
          {
            name: 'Battle ropes',
            muscleGroup: 'Cuerpo completo',
            sets: 4,
            reps: '30s',
            restSeconds: 45,
          },
          {
            name: 'Incline treadmill',
            muscleGroup: 'Cardio',
            sets: 1,
            reps: '15min',
            restSeconds: 0,
          },
        ],
      },
      {
        name: 'Día B — Fuerza inferior + cardio',
        exercises: [
          {
            name: 'Goblet squat',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '12-15',
            restSeconds: 75,
          },
          {
            name: 'Dumbbell hip thrust',
            muscleGroup: 'Glúteo',
            sets: 4,
            reps: '15',
            restSeconds: 60,
          },
          {
            name: 'Dumbbell walking lunge',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '12/leg',
            restSeconds: 60,
          },
          {
            name: 'Stationary bike HIIT',
            muscleGroup: 'Cardio',
            sets: 6,
            reps: '30s on / 30s off',
            restSeconds: 0,
          },
        ],
      },
      {
        name: 'Día C — Circuito metabólico',
        exercises: [
          {
            name: 'Kettlebell swing',
            muscleGroup: 'Cuerpo completo',
            sets: 4,
            reps: '15',
            restSeconds: 45,
          },
          {
            name: 'Burpee',
            muscleGroup: 'Cuerpo completo',
            sets: 4,
            reps: '12',
            restSeconds: 45,
          },
          {
            name: 'Dumbbell push press',
            muscleGroup: 'Hombro',
            sets: 4,
            reps: '12',
            restSeconds: 45,
          },
          {
            name: 'Mountain climber',
            muscleGroup: 'Core',
            sets: 4,
            reps: '40s',
            restSeconds: 45,
          },
          {
            name: 'Box jump',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '10',
            restSeconds: 60,
          },
        ],
      },
      {
        name: 'Día D — Cardio largo + core',
        exercises: [
          {
            name: 'Treadmill steady pace',
            muscleGroup: 'Cardio',
            sets: 1,
            reps: '30min',
            restSeconds: 0,
          },
          {
            name: 'Front plank',
            muscleGroup: 'Core',
            sets: 3,
            reps: '45-60s',
            restSeconds: 45,
          },
          {
            name: 'Side plank',
            muscleGroup: 'Core',
            sets: 3,
            reps: '30s/side',
            restSeconds: 45,
          },
          {
            name: 'Cable crunch',
            muscleGroup: 'Core',
            sets: 3,
            reps: '15',
            restSeconds: 45,
          },
          {
            name: 'Bird dog',
            muscleGroup: 'Core',
            sets: 3,
            reps: '12/side',
            restSeconds: 45,
          },
        ],
      },
    ],
  },
  {
    id: 'fat-home-4d',
    name: 'Quema grasa funcional — Casa 4 días',
    description:
      'Circuitos en casa con mancuernas. Sesiones cortas e intensas para perder grasa empezando.',
    goal: 'LOSE_FAT',
    equipment: 'HOME_WEIGHTS',
    level: 'BEGINNER',
    daysPerWeek: 4,
    estimatedDurationMin: 35,
    routines: [
      {
        name: 'Circuito A — Tren completo',
        exercises: [
          {
            name: 'Goblet squat',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '12',
            restSeconds: 30,
          },
          {
            name: 'Dumbbell floor press',
            muscleGroup: 'Pecho',
            sets: 4,
            reps: '12',
            restSeconds: 30,
          },
          {
            name: 'One-arm dumbbell row',
            muscleGroup: 'Espalda',
            sets: 4,
            reps: '12/side',
            restSeconds: 30,
          },
          {
            name: 'Burpee',
            muscleGroup: 'Cuerpo completo',
            sets: 4,
            reps: '10',
            restSeconds: 45,
          },
        ],
      },
      {
        name: 'Circuito B — Pierna y core',
        exercises: [
          {
            name: 'Dumbbell walking lunge',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '10/leg',
            restSeconds: 30,
          },
          {
            name: 'Dumbbell hip thrust',
            muscleGroup: 'Glúteo',
            sets: 4,
            reps: '15',
            restSeconds: 30,
          },
          {
            name: 'Mountain climber',
            muscleGroup: 'Core',
            sets: 4,
            reps: '30s',
            restSeconds: 30,
          },
          {
            name: 'Front plank',
            muscleGroup: 'Core',
            sets: 3,
            reps: '30-45s',
            restSeconds: 30,
          },
        ],
      },
      {
        name: 'Circuito C — Tren superior',
        exercises: [
          {
            name: 'Dumbbell shoulder press',
            muscleGroup: 'Hombro',
            sets: 4,
            reps: '12',
            restSeconds: 30,
          },
          {
            name: 'Dumbbell bicep curl',
            muscleGroup: 'Bíceps',
            sets: 3,
            reps: '12',
            restSeconds: 30,
          },
          {
            name: 'Triceps kickback',
            muscleGroup: 'Tríceps',
            sets: 3,
            reps: '12',
            restSeconds: 30,
          },
          {
            name: 'Dumbbell floor fly',
            muscleGroup: 'Pecho',
            sets: 3,
            reps: '12',
            restSeconds: 30,
          },
          {
            name: 'Side plank',
            muscleGroup: 'Core',
            sets: 3,
            reps: '30s/side',
            restSeconds: 30,
          },
        ],
      },
      {
        name: 'Circuito D — HIIT',
        exercises: [
          {
            name: 'Burpee',
            muscleGroup: 'Cuerpo completo',
            sets: 5,
            reps: '40s on / 20s off',
            restSeconds: 0,
          },
          {
            name: 'Jump squat',
            muscleGroup: 'Pierna',
            sets: 5,
            reps: '40s on / 20s off',
            restSeconds: 0,
          },
          {
            name: 'Mountain climber',
            muscleGroup: 'Core',
            sets: 5,
            reps: '40s on / 20s off',
            restSeconds: 0,
          },
          {
            name: 'High knees',
            muscleGroup: 'Cardio',
            sets: 5,
            reps: '40s on / 20s off',
            restSeconds: 0,
          },
        ],
      },
    ],
  },
  {
    id: 'fat-bw-5d',
    name: 'Quema grasa — Bodyweight 5 días',
    description:
      'Circuitos diarios con peso corporal. Cinco sesiones cortas para acelerar la pérdida de grasa.',
    goal: 'LOSE_FAT',
    equipment: 'BODYWEIGHT',
    level: 'INTERMEDIATE',
    daysPerWeek: 5,
    estimatedDurationMin: 30,
    routines: [
      {
        name: 'Tabata cuerpo completo',
        exercises: [
          {
            name: 'Burpee',
            muscleGroup: 'Cuerpo completo',
            sets: 8,
            reps: '20s on / 10s off',
            restSeconds: 0,
          },
          {
            name: 'Jumping jack',
            muscleGroup: 'Cardio',
            sets: 8,
            reps: '20s on / 10s off',
            restSeconds: 0,
          },
          {
            name: 'Jump squat',
            muscleGroup: 'Pierna',
            sets: 8,
            reps: '20s on / 10s off',
            restSeconds: 0,
          },
          {
            name: 'Mountain climber',
            muscleGroup: 'Core',
            sets: 8,
            reps: '20s on / 10s off',
            restSeconds: 0,
          },
        ],
      },
      {
        name: 'Circuito tren superior',
        exercises: [
          {
            name: 'Push-up',
            muscleGroup: 'Pecho',
            sets: 4,
            reps: '15',
            restSeconds: 30,
          },
          {
            name: 'Inverted row',
            muscleGroup: 'Espalda',
            sets: 4,
            reps: '12',
            restSeconds: 30,
          },
          {
            name: 'Pike push-up',
            muscleGroup: 'Hombro',
            sets: 3,
            reps: '10-12',
            restSeconds: 30,
          },
          {
            name: 'Bench dip',
            muscleGroup: 'Tríceps',
            sets: 3,
            reps: '12',
            restSeconds: 30,
          },
          {
            name: 'Front plank',
            muscleGroup: 'Core',
            sets: 3,
            reps: '45s',
            restSeconds: 30,
          },
        ],
      },
      {
        name: 'Circuito tren inferior',
        exercises: [
          {
            name: 'Bodyweight squat',
            muscleGroup: 'Pierna',
            sets: 5,
            reps: '20',
            restSeconds: 30,
          },
          {
            name: 'Alternating lunge',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '12/leg',
            restSeconds: 30,
          },
          {
            name: 'Bulgarian split squat',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '12/leg',
            restSeconds: 30,
          },
          {
            name: 'Jump squat',
            muscleGroup: 'Pierna',
            sets: 4,
            reps: '15',
            restSeconds: 30,
          },
          {
            name: 'Single-leg calf raise',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '20/leg',
            restSeconds: 30,
          },
        ],
      },
      {
        name: 'EMOM 20 minutos',
        exercises: [
          {
            name: 'Burpee',
            muscleGroup: 'Cuerpo completo',
            sets: 5,
            reps: '8 every minute',
            restSeconds: 0,
          },
          {
            name: 'Push-up',
            muscleGroup: 'Pecho',
            sets: 5,
            reps: '12 every minute',
            restSeconds: 0,
          },
          {
            name: 'Bodyweight squat',
            muscleGroup: 'Pierna',
            sets: 5,
            reps: '15 every minute',
            restSeconds: 0,
          },
          {
            name: 'Mountain climber',
            muscleGroup: 'Core',
            sets: 5,
            reps: '30 every minute',
            restSeconds: 0,
          },
        ],
      },
      {
        name: 'Cardio + core',
        exercises: [
          {
            name: 'High knees',
            muscleGroup: 'Cardio',
            sets: 4,
            reps: '60s',
            restSeconds: 30,
          },
          {
            name: 'Jumping jack',
            muscleGroup: 'Cardio',
            sets: 4,
            reps: '60s',
            restSeconds: 30,
          },
          {
            name: 'Front plank',
            muscleGroup: 'Core',
            sets: 3,
            reps: '60s',
            restSeconds: 45,
          },
          {
            name: 'Bird dog',
            muscleGroup: 'Core',
            sets: 3,
            reps: '12/side',
            restSeconds: 30,
          },
          {
            name: 'Hollow hold',
            muscleGroup: 'Core',
            sets: 3,
            reps: '30s',
            restSeconds: 30,
          },
        ],
      },
    ],
  },
  {
    id: 'health-gym-3d',
    name: 'Salud y movilidad — Gimnasio 3 días',
    description:
      'Trabajo general en gimnasio enfocado en mantenerse activo, sano y con buena movilidad.',
    goal: 'HEALTH',
    equipment: 'FULL_GYM',
    level: 'BEGINNER',
    daysPerWeek: 3,
    estimatedDurationMin: 45,
    routines: [
      {
        name: 'Día A',
        exercises: [
          {
            name: 'Goblet squat',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '12-15',
            restSeconds: 60,
          },
          {
            name: 'Incline dumbbell bench press',
            muscleGroup: 'Pecho',
            sets: 3,
            reps: '10-12',
            restSeconds: 60,
          },
          {
            name: 'Machine row',
            muscleGroup: 'Espalda',
            sets: 3,
            reps: '10-12',
            restSeconds: 60,
          },
          {
            name: 'Treadmill brisk walk',
            muscleGroup: 'Cardio',
            sets: 1,
            reps: '15min',
            restSeconds: 0,
          },
          {
            name: 'General stretching',
            muscleGroup: 'Movilidad',
            sets: 1,
            reps: '10min',
            restSeconds: 0,
          },
        ],
      },
      {
        name: 'Día B',
        exercises: [
          {
            name: 'Dumbbell Romanian deadlift',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '10-12',
            restSeconds: 75,
          },
          {
            name: 'Machine shoulder press',
            muscleGroup: 'Hombro',
            sets: 3,
            reps: '10-12',
            restSeconds: 60,
          },
          {
            name: 'Lat pulldown',
            muscleGroup: 'Espalda',
            sets: 3,
            reps: '10-12',
            restSeconds: 60,
          },
          {
            name: 'Front plank',
            muscleGroup: 'Core',
            sets: 3,
            reps: '30-45s',
            restSeconds: 45,
          },
          {
            name: 'Easy stationary bike',
            muscleGroup: 'Cardio',
            sets: 1,
            reps: '15min',
            restSeconds: 0,
          },
        ],
      },
      {
        name: 'Día C',
        exercises: [
          {
            name: 'Machine hip thrust',
            muscleGroup: 'Glúteo',
            sets: 3,
            reps: '12-15',
            restSeconds: 60,
          },
          {
            name: 'Cable fly',
            muscleGroup: 'Pecho',
            sets: 3,
            reps: '12-15',
            restSeconds: 45,
          },
          {
            name: 'Reverse pec deck',
            muscleGroup: 'Hombro',
            sets: 3,
            reps: '12-15',
            restSeconds: 45,
          },
          {
            name: 'Bird dog',
            muscleGroup: 'Core',
            sets: 3,
            reps: '10/side',
            restSeconds: 45,
          },
          {
            name: 'Hip and shoulder mobility',
            muscleGroup: 'Movilidad',
            sets: 1,
            reps: '10min',
            restSeconds: 0,
          },
        ],
      },
    ],
  },
  {
    id: 'maint-home-3d',
    name: 'Mantenimiento — Casa con pesos 3 días',
    description:
      'Tres sesiones cortas en casa para mantener fuerza y forma física sin ir al gimnasio.',
    goal: 'MAINTAIN',
    equipment: 'HOME_WEIGHTS',
    level: 'BEGINNER',
    daysPerWeek: 3,
    estimatedDurationMin: 35,
    routines: [
      {
        name: 'Día A',
        exercises: [
          {
            name: 'Goblet squat',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '10-12',
            restSeconds: 60,
          },
          {
            name: 'Dumbbell floor press',
            muscleGroup: 'Pecho',
            sets: 3,
            reps: '10-12',
            restSeconds: 60,
          },
          {
            name: 'One-arm dumbbell row',
            muscleGroup: 'Espalda',
            sets: 3,
            reps: '10-12',
            restSeconds: 60,
          },
          {
            name: 'Front plank',
            muscleGroup: 'Core',
            sets: 3,
            reps: '30-45s',
            restSeconds: 45,
          },
        ],
      },
      {
        name: 'Día B',
        exercises: [
          {
            name: 'Dumbbell Romanian deadlift',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '10-12',
            restSeconds: 75,
          },
          {
            name: 'Seated dumbbell shoulder press',
            muscleGroup: 'Hombro',
            sets: 3,
            reps: '10-12',
            restSeconds: 60,
          },
          {
            name: 'Dumbbell bicep curl',
            muscleGroup: 'Bíceps',
            sets: 3,
            reps: '10-12',
            restSeconds: 45,
          },
          {
            name: 'Triceps kickback',
            muscleGroup: 'Tríceps',
            sets: 3,
            reps: '10-12',
            restSeconds: 45,
          },
        ],
      },
      {
        name: 'Día C',
        exercises: [
          {
            name: 'Bulgarian split squat (dumbbells)',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '10/leg',
            restSeconds: 75,
          },
          {
            name: 'Dumbbell hip thrust',
            muscleGroup: 'Glúteo',
            sets: 3,
            reps: '12-15',
            restSeconds: 60,
          },
          {
            name: 'Dumbbell floor fly',
            muscleGroup: 'Pecho',
            sets: 3,
            reps: '10-12',
            restSeconds: 45,
          },
          {
            name: 'Dumbbell rear delt fly',
            muscleGroup: 'Hombro',
            sets: 3,
            reps: '12-15',
            restSeconds: 45,
          },
          {
            name: 'Side plank',
            muscleGroup: 'Core',
            sets: 3,
            reps: '30s/side',
            restSeconds: 45,
          },
        ],
      },
    ],
  },
  {
    id: 'mob-bw-4d',
    name: 'Movilidad y core — Bodyweight 4 días',
    description:
      'Sesiones cortas centradas en movilidad, core y trabajo cardiovascular suave. Sin material.',
    goal: 'HEALTH',
    equipment: 'BODYWEIGHT',
    level: 'BEGINNER',
    daysPerWeek: 4,
    estimatedDurationMin: 30,
    routines: [
      {
        name: 'Día A — Movilidad',
        exercises: [
          {
            name: 'Cat-cow stretch',
            muscleGroup: 'Movilidad',
            sets: 3,
            reps: '10',
            restSeconds: 30,
          },
          {
            name: 'Lying thoracic rotation',
            muscleGroup: 'Movilidad',
            sets: 3,
            reps: '8/side',
            restSeconds: 30,
          },
          {
            name: '90/90 hip stretch',
            muscleGroup: 'Movilidad',
            sets: 3,
            reps: '8/side',
            restSeconds: 30,
          },
          {
            name: "World's greatest stretch",
            muscleGroup: 'Movilidad',
            sets: 3,
            reps: '6/side',
            restSeconds: 30,
          },
          {
            name: 'Moderate-pace walk',
            muscleGroup: 'Cardio',
            sets: 1,
            reps: '15min',
            restSeconds: 0,
          },
        ],
      },
      {
        name: 'Día B — Core',
        exercises: [
          {
            name: 'Front plank',
            muscleGroup: 'Core',
            sets: 3,
            reps: '30-45s',
            restSeconds: 45,
          },
          {
            name: 'Side plank',
            muscleGroup: 'Core',
            sets: 3,
            reps: '20-30s/side',
            restSeconds: 45,
          },
          {
            name: 'Bird dog',
            muscleGroup: 'Core',
            sets: 3,
            reps: '10/side',
            restSeconds: 30,
          },
          {
            name: 'Dead bug',
            muscleGroup: 'Core',
            sets: 3,
            reps: '10/side',
            restSeconds: 30,
          },
          {
            name: 'Hollow hold',
            muscleGroup: 'Core',
            sets: 3,
            reps: '20-30s',
            restSeconds: 30,
          },
        ],
      },
      {
        name: 'Día C — Cuerpo completo suave',
        exercises: [
          {
            name: 'Bodyweight squat',
            muscleGroup: 'Pierna',
            sets: 3,
            reps: '15',
            restSeconds: 45,
          },
          {
            name: 'Incline push-up',
            muscleGroup: 'Pecho',
            sets: 3,
            reps: '10-12',
            restSeconds: 45,
          },
          {
            name: 'Inverted row',
            muscleGroup: 'Espalda',
            sets: 3,
            reps: '10',
            restSeconds: 45,
          },
          {
            name: 'Glute bridge',
            muscleGroup: 'Glúteo',
            sets: 3,
            reps: '15',
            restSeconds: 30,
          },
          {
            name: 'Moderate-pace walk',
            muscleGroup: 'Cardio',
            sets: 1,
            reps: '10min',
            restSeconds: 0,
          },
        ],
      },
      {
        name: 'Día D — Yoga / movilidad',
        exercises: [
          {
            name: 'Sun salutation',
            muscleGroup: 'Movilidad',
            sets: 3,
            reps: '5 cycles',
            restSeconds: 30,
          },
          {
            name: "Child's pose",
            muscleGroup: 'Movilidad',
            sets: 3,
            reps: '60s',
            restSeconds: 30,
          },
          {
            name: 'Piriformis stretch',
            muscleGroup: 'Movilidad',
            sets: 3,
            reps: '45s/side',
            restSeconds: 30,
          },
          {
            name: 'Downward dog',
            muscleGroup: 'Movilidad',
            sets: 3,
            reps: '45s',
            restSeconds: 30,
          },
          {
            name: 'Diaphragmatic breathing',
            muscleGroup: 'Movilidad',
            sets: 1,
            reps: '5min',
            restSeconds: 0,
          },
        ],
      },
    ],
  },
];
